### ISSUE TITLE
Document how to update `sbfspot` to a new version

### ISSUE THREAD

**Issue by wimleers** [nakla/sbfspot#17]
It seems I've got `sbfspot` 3.8.4, which dates back to December 2021: https://github.com/SBFspot/SBFspot/wiki/Modification-History#384-11-dec-2021-bugfix-release

I have no idea how I got this version, because A) there's no mention of this version anywhere int his repo, B) I installed `nakla/sbfspot` long after this date. It _is_ the first `sbfspot` release after the last commit to this repo though, so I suspect that's the reason.

So: how does one update to a new version of `sbfspot`?

Maybe this is obvious to expert Docker users, but it is not to me 😅

**Comment by nakla** [comment]
Hi, if you use my docker container, there is currently no newer version - I also use 3.8.4 in it. But you can go to github and build your own container based on my files if you need a newer SBFspot version. Other option is you wait until I build a new Version, but I don't know when I have got the time therefore, as the actual version works for me without problems.

 
 

Gesendet: Samstag, 19. November 2022 um 15:48 Uhr
Von: "Wim Leers" ***@***.***>
An: "nakla/sbfspot" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [nakla/sbfspot] Document how to update `sbfspot` to a new version (Issue #17)


 

It seems I've got sbfspot 3.8.4, which dates back to December 2021: https://github.com/SBFspot/SBFspot/wiki/Modification-History#384-11-dec-2021-bugfix-release

I have no idea how I got this version, because A) there's no mention of this version anywhere int his repo, B) I installed nakla/sbfspot long after this date. It is the first sbfspot release after the last commit to this repo though, so I suspect that's the reason.

So: how does one update to a new version of sbfspot?

Maybe this is obvious to expert Docker users, but it is not to me 😅
